##the db
version: '2'
services:
  app:
  
    container_name: mysql_database
    image: mysql:5.7
    volumes:
        - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=laravel-db"
      - "MY_SQL_USER=admin"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - 8991:3306
